apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-vertx
  namespace: buildstuff-workshop
spec:
  template:
    metadata:
      name: helloworld-vertx-v1
    spec:
       containers:
         - image: docker.io/mgrygles/buildstuff2020
           env:
             - name: TARGET
               value: "Eclipse Vert.x helloworld BuildStuff2020 Friends"

